"""add is_active and realm_resource realm_acl tables

Revision ID: 374dcd9107e4
Revises: e8f9a6c4d2b1
Create Date: 2025-12-17 00:19:37.616456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '374dcd9107e4'
down_revision: Union[str, Sequence[str], None] = 'e8f9a6c4d2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('realm_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.Column('resource_type_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['principal.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], ),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resource_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('realm_acl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('principal_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.ForeignKeyConstraint(['principal_id'], ['principal.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['realm_resource.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Constraints and Columns
    op.drop_constraint('action_realm_id_name_key', 'action', type_='unique')
    op.create_unique_constraint('uq_action_realm_name', 'action', ['realm_id', 'name'])
    
    # Check if ix_principal_attributes exists before dropping?
    # It was autogenerated, so it likely exists.
    op.drop_index('ix_principal_attributes', table_name='principal', postgresql_using='gin')
    
    op.add_column('realm', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    
    op.drop_constraint('resource_type_realm_id_name_key', 'resource_type', type_='unique')
    op.create_unique_constraint('uq_resource_type_realm_name', 'resource_type', ['realm_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_resource_type_realm_name', 'resource_type', type_='unique')
    op.create_unique_constraint('resource_type_realm_id_name_key', 'resource_type', ['realm_id', 'name'], postgresql_nulls_not_distinct=False)
    
    op.drop_column('realm', 'is_active')
    
    op.create_index('ix_principal_attributes', 'principal', ['attributes'], unique=False, postgresql_using='gin')
    
    op.drop_constraint('uq_action_realm_name', 'action', type_='unique')
    op.create_unique_constraint('action_realm_id_name_key', 'action', ['realm_id', 'name'], postgresql_nulls_not_distinct=False)
    
    op.drop_table('realm_acl')
    op.drop_table('realm_resource')
    # ### end Alembic commands ###
